travis:
  secure:
    BINSTAR_TOKEN: tzhrEHZuIz7lRzMNaVMSMUC47FgF0GZDEmNveztFtJfstXKK3+MxM7ay/sDRTOY5KAUXCk1llhsudOxXSONdV8cGVPDNO3WQ/HdmJ4XFbtrTpVWwRbAMTgE1RjfW5sQ8sfzgDpZvQZ/nmxcOW2HCp+gDeaqfkUNiEeGHL57pNvMJ+O5JyYAE8JHveNSJH7hwMSLjPhNpIniibQbKO7i/VdRCh60wSigkirnog8VaHEROZP4h580Mn3t2Tm+x3bGQ7q4D7Ej/hkuoA0e1HsXIwB/68g/WciTZNUSpMHt60XPiwu50y0nn0LspFra2aOcugC2oEBNwnbtQ7nHyQ5O7OC0jduMGI05doSbmag6WyZJ5i1Ks/6JxDmlZ7oOgecqv0V9nYOuAkQnETMXDsifDdOFPn8FV5ePOy88xUmUIXiUoYISzZiqVcbAcwP5JACsVAc68aLRNBijdmwQRKCFtWOtyXoPztlqL6P5K7J2xXRIAjqqv2IZ5uGNuY7dCl2yyJ+FrKn0VevQuJLDFnT+H82eLpdh6Io5iuQIhmb/Gk7M5Ujrph6HtbcR6f8megYVDtovZ0KqW1DE5D+BWYRLAHWsxV1B8vah6P8BS37VKSsD9Pfg8whx47Djxybvu9Z774zAf+nA8mvjpOGdtY0AsNDQEMkXtV0rZOkbPnZ8f5xM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
